site_name: GEO1003 - Shared Notes
theme:
  name: material
  features:
    - navigation.instant

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_truly_sane_lists

plugins:
  - search
  - caption

# Define navigation and documentation structure
nav:
  - Concise version:
    - "chapters/intro.md"
    - Chapters:
      - Example:
        - Introduction: "chapters/example/intro.md"
        - Mardown Basics: "chapters/example/markdown_basics.md"
        - Empty Section: "chapters/example/empty_section.md"
    - PDF version: "pdf/notes.pdf"
  - Long version:
    - "chapters/intro-long.md"
    - Chapters:
      - Example:
        - Introduction: "chapters/example/intro-long.md"
        - Mardown Basics: "chapters/example/markdown_basics-long.md"
        - Empty Section: "chapters/example/empty_section-long.md"
    - PDF version: "pdf/notes-long.pdf"
