site_name: GEO1003 - Shared Notes
theme:
  name: readthedocs
  features:
    - navigation.instant

# Define navigation and documentation structure
nav:
  - "chapters/intro.md"
  - Chapters:
    - "Examples":
      - "chapters/example/intro.md"
      - "chapters/example/markdown_basics.md"
      - "chapters/example/empty_section.md"

