site_name: GEO1003 - Shared Notes
theme:
  name: readthedocs
  features:
    - navigation.instant

# markdown_extensions:
#   - pymdownx.superfences
#   - codehilite:
#       guess_lang: false
#   - attr_list

# extra_css:
#   - css/custom.css

# Define navigation and documentation structure
nav:
  - "chapters/intro.md"
  - Chapters:
    - "Examples":
      - "chapters/example/intro.md"
      - "chapters/example/markdown_basics.md"
      - "chapters/example/empty_section.md"

