name: Pandoc PDF Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pandoc:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and install the latest Pandoc
      run: |
        if [ ! -f /usr/local/bin/pandoc ]; then
          wget https://github.com/jgm/pandoc/releases/download/3.5/pandoc-3.5-linux-amd64.tar.gz -O pandoc.tar.gz
          tar xzf pandoc.tar.gz
          mv pandoc-3.5/bin/pandoc /usr/local/bin/
          chmod +x /usr/local/bin/pandoc
          sudo apt-get install texlive-xetex texlive-fonts-recommended
        fi

    - name: Cache Pandoc
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/pandoc
        key: pandoc-$(echo "3.5" | tr -d .)
        restore-keys: |
          pandoc-
    - name: Cache TeXLive
      uses: actions/cache@v4
      with:
        path: /usr/share/texlive
        key: texlive-$(md5sum /etc/lsb-release | cut -d' ' -f1)
        restore-keys: |
          texlive-

    - name: Install dependencies
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Generate PDF with Pandoc
      run: |
        cd docs
        bash ./bash/export_notes.sh
        bash ./bash/export_notes_long.sh
      timeout-minutes: 5  # Increase timeout to accommodate longer execution times
