name: Pandoc PDF Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pandoc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and install the latest Pandoc
      run: |
        wget https://github.com/jgm/pandoc/releases/download/3.5/pandoc-3.5-linux-amd64.tar.gz -O pandoc.tar.gz
        tar xzf pandoc.tar.gz
        mv pandoc-3.5/bin/pandoc /usr/local/bin/
        chmod +x /usr/local/bin/pandoc
        pandoc --version

    - name: Install dependencies
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Generate PDF with Pandoc
      run: |
        cd docs
        bash ./bash/export_notes.sh
        bash ./bash/export_notes_long.sh
