name: Pandoc PDF Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pandoc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Pandoc
      uses: actions/cache@v2
      with:
        path: /usr/local/bin/pandoc
        key: pandoc-$(echo "3.5" | tr -d .)
        restore-keys: |
          pandoc-

    - name: Cache TeX Live
      uses: actions/cache@v2
      with:
        path: /usr/share/texlive
        key: texlive-$(md5sum /etc/lsb-release | cut -d' ' -f1)
        restore-keys: |
          texlive-

    - name: Install dependencies
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Generate PDF with Pandoc
      run: |
        cd docs
        bash ./bash/export_notes.sh
        bash ./bash/export_notes_long.sh
      timeout-minutes: 5
